### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [felipec/zsh-prompt-felipec#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by felipec** [comment]
@unixorn I'm not exactly sure what I should showcase in the screenshot, would this be good enough: [screenshot](https://i.imgur.com/5KY1iMT.png)?

As for the license I like [ISC](https://opensource.org/license/isc-license-txt) which is very simple and most people seem to be OK with it. Would that be OK for you?

**Comment by unixorn** [comment]
That's perfect, thanks
